name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Налаштування JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Запуск тестів
      - name: Run tests
        run: |
          ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Simulate deploy
        run: echo "Deployed"
