name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Compile the code
        run: javac -d bin src/com/example/*.java

      - name: Run tests
        run: |
          javac -cp bin:junit-4.13.2.jar:hamcrest-core-1.3.jar -d bin src/com/example/CalculatorTest.java
          java -cp bin:junit-4.13.2.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore com.example.CalculatorTest

      - name: Deploy
        if: success()
        run: echo "Deployed!"
